### PR TITLE
Port to .NET Core, ReSharper cleanups, and switched to xUnit

### PR DESCRIPTION
**Pull request by wonea**
The NuGet package needs updating

### CODE REVIEW

**Comment by JamieDixon** [comment]
Hi Gareth,

Thanks for submitting this PR. I'm really happy to see someone taking an interest in this project! I'll aim to take a look over the next couple of days and get this merged. I don't currently have a way to test this (I'm on a Mac now) but maybe I can find a way.

Thanks, Jamie

**Comment by wonea** [comment]
Thank you for making this wrapper.

I haven't tried it, but apparently the new JetBrains .NET IDE runs on the Mac.
https://www.jetbrains.com/rider/

**Comment by wonea** [comment]
You could use Visual Studio Code? Works well with NET Standard.

**Comment by wonea** [comment]
If I simplified this pull request with just the project files changed to NETSTANDARD would this be appropriate? Could also add both NET46 and NETSTANDARD20 if appropriate.

**Pull request closed without merging**
